### ISSUE TITLE
[Question] Different backgrounds

### ISSUE THREAD

**Issue by waxfingers** [nriley/Shroud#3]
First off, thank you for this simple and useful tool 👍👍
Then, is there an easy way (layman man here) to select a different background?
Is it possible to change it? I went inside the app looking for the image but could not find any, maybe it's rendered in the moment... also I'd love to be able to display floating transparent images (png and gifs).
That's all. Cheers 😃

**Comment by nriley** [comment]
Yeah, Shroud is a solid-color background.  Images are distracting for me at least!  If you want an image as a background, you might check out Desktop Curtain.

https://manytricks.com/desktopcurtain/ <https://manytricks.com/desktopcurtain/>
